travis:
  secure:
    BINSTAR_TOKEN: E9U6E/MfYsaFCtUtP6096E7kCm6EXFYDx50MUNxQu7nK/VkMPT5URmBDAOXwkn7y/Wg1O6bUIhrc/GaOSe0FS7lqM6UJm1sjG+Eu4Fa+v1lqlLWPftDiQ1JpbEgJTHxZCiIEJBrdYGR/rz3dFl4v2xHTs9JGNt+9C3Rdr4sszDaLg1OFlUfvm9TzPnIM0ecZPACY6FaJDSROIAHiCqc9DRaxrXgiSTSrcctQXJZguuxMLzVnSdEkRAeeYwsrdD+nhSHhqSGUPUihiumtoDowYI1FUoXYLw+dcFynK4RoKIh9Lu6L+lzEWw1B2CoHjDWQ5yP/HNPmHmEPRp6V9xBgU13Jv3hAEh35Xn57+fsz+pq7y1OyZy1QXj53mV09XN59zNsh+1DIjhP6XSp+bJEGtuuDUDTStGv92lTs08lwrid1YL88U8HwHRD0E5OmmtJ2XKyIzUd8mhfgbIq3kNeg0JkodI6KiZPsJAYVQerYJ5RLs7hCbEiXw0+clfSjV1VAhkT8oecZ6YHL/Boz7BQ8lYZwDSp3GpMAZdnaynVFRhWr9V4jCAMwiI2ULV6dxLeKrENkiBN+PRUqrR9DjKyVQzvSF3cqMooDG5gZcIL4ZGl1QhoUqtzVaoS8GVCG0CRgsgyEHtbCpFbXI33yJNw4daXeFRxSElnIToDxfr/5eQM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
